// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inchlsvnvdotbxqnsxmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluY2hsc3ZudmRvdGJ4cW5zeG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzIyMDUsImV4cCI6MjA4ODM0ODIwNX0.Q0Mfze90R00FdgNTF67bwy9x24aDbllA0QbeqKVkd-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});